"""empty message

Revision ID: 211659f8f0a0
Revises: f72e6b27690d
Create Date: 2023-03-28 19:54:35.665414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211659f8f0a0'
down_revision = 'f72e6b27690d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
