"""empty message

Revision ID: 330b6de658e3
Revises: 1a744e1f14a9
Create Date: 2023-04-01 19:23:49.302937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330b6de658e3'
down_revision = '1a744e1f14a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    # ### end Alembic commands ###
